# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none
pr: none

pool:
  vmImage: ubuntu-latest

steps:

- script: |
    set -x
    echo "Setup Summary.md"
    cat <<-EOF > /tmp/summary.md
      Summary
      ======
      - Created resources: 0
      - Deleted resources: 0
      - Updated resources: 0
      - Unchanged resources: 117
      - Skipped resources: 1
    EOF
    cat /tmp/summary.md
    ls -la /tmp

- script: |
    ls -la /tmp
    echo "##vso[task.uploadsummary]/tmp/summary.md"
  displayName: 'Change summary page'
