# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none
pr: none

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    GIT_COMMIT=$( git rev-parse --short HEAD )
    echo "##vso[task.setvariable variable=GIT_COMMIT;isOutput=true]$GIT_COMMIT"
  name: runtime_vars
  displayName: 'Set runtime variables for pipeline'

- script: |
    echo "Setup github.md"
    cat <<-EOF > $(Agent.BuildDirectory)/github.md
      Summary
      ======
      - GIT_VERSION: $(runtime_vars.GIT_COMMIT)
    EOF
    cat $(Agent.BuildDirectory)/github.md

- script: |
    echo "##vso[task.uploadsummary]$(Agent.BuildDirectory)/github.md"
  displayName: 'Change summary page'